language: r
r:
  - release
  - devel

sudo: required

cache: packages

warnings_are_errors: true

before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq qpdf

env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--resave-data --compact-vignettes=gs+qpdf"
   - R_CHECK_ARGS="--as-cran"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'