language: r
r:
  - release
  - devel

sudo: false
cran: http://cran.at.r-project.org

cache: packages

warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--compact-vignettes=gs+qpdf"
   - R_CHECK_ARGS="--as-cran"

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'